### ISSUE TITLE
Error on MN during initialization due to invalid default path

### ISSUE THREAD

**Issue by alexbarcelo** [bsc-dom/dataclay-packaging#95]
The current codebase, once deployed on Mare Nostrum, doesn't behave nicely on filesystem matters.

The traceback given is:

```
Traceback (most recent call last):
  File "/apps/PYTHON/3.6.4_ML/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/apps/PYTHON/3.6.4_ML/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/apps/DATACLAY/2.6/pyclay/src/dataclay/executionenv/server/__main__.py", line 30, in <module>
    run_main()
  File "/apps/DATACLAY/2.6/pyclay/src/dataclay/executionenv/server/__main__.py", line 26, in run_main
    exec_env_srv.start()
  File "/apps/DATACLAY/2.6/pyclay/src/dataclay/executionenv/server/ExecutionEnvironmentSrv.py", line 208, in start
    self.execution_environment = ExecutionEnvironment(settings.dataservice_name)
  File "/apps/DATACLAY/2.6/pyclay/src/dataclay/executionenv/ExecutionEnvironment.py", line 60, in __init__
    self.store_ee_info()
  File "/apps/DATACLAY/2.6/pyclay/src/dataclay/executionenv/ExecutionEnvironment.py", line 89, in store_ee_info
    fh = open(info_file, 'w')
OSError: [Errno 30] Read-only file system: '/dataclay/metadata//python_ee_dataservice1.info'
```

AFAICT, the `/dataclay` path is used by default in containerized environment and so on, but that won't work on Mare Nostrum or other cluster deployments. I don't know if singularity is involved in all that. I think so. I don't know if it has any impact.

The 2.5 deployment is currently working, but I cannot assure if there is some regression problem or there were some manual fine-tuning on the 2.5 deployment that have not been done on 2.6.

**Comment by daniwhere** [comment]
Absolutely right, it was a bug in 2.6 version. Current version stores logicmodule metadata databases like classes, operations, contracts,... in a different path than object metadata and sessions databases. So, we have `/dataclay/storage/` for object data and `/dataclay/metadata` for class-model data. This was done to add fault tolerance support in case we loose the `storage` database. This new path was not added in `orchestration` scripts, adding it now.  

 Fixed in bsc-dom/dataclay-orchestration@cbd6476f19c76d4111ab7c5e47368e4444ce56c8 .Fix was deployed to MN.

@alexbarcelo can you retry it and confirm that it works for you?
